### ISSUE TITLE
verbs cut off for kanien'kéha

### ISSUE THREAD

**Issue by roedoejet** [WordWeaverTools/wordweaver#23]
**To Reproduce**
Add verbs with KA selected as language

**Expected behavior**
Must be able to delete verbs

**Screenshots**

![image](https://user-images.githubusercontent.com/14815080/178813492-d10ced4d-6088-4997-aaef-7834fe52b496.png)

**Additional context**
Sent by Akwiratékha'

**Comment by dlothian** [comment]
![image](https://github.com/roedoejet/wordweaver-UI/assets/22920735/ff9e8b7f-54f6-432a-a4d3-f3e95f40fcc8)

**Comment by dlothian** [comment]
![image](https://github.com/roedoejet/wordweaver-UI/assets/22920735/6045e128-4b4b-4204-a4cf-f340126b76ca)

**Comment by dlothian** [comment]
![image](https://github.com/roedoejet/wordweaver-UI/assets/22920735/1ed0399b-4119-4b2b-ac19-596be276e8da)
